---

- name: Check the namespace
  assert:
    that:
    - spp_namespace | string | length > 0

- name: Creating namespace '{{ spp_namespace }}'
  k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

- name: Deploy ServiceAccount
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - role
  - rolebinding-sa

- name: Deploy Role and RoleBinding
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - role
  - rolebinding-sa
  when: spp_sa_psp | string | length > 0

- name: Deploy the SmokePing Prober
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - configmap
  - deployment
  - service
  - servicemonitor
