---

- include_tasks: prep.yaml

# A kubernetes host and an API key must be set.
# Either K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables
# or a KUBECONFIG environment variable must be set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host | length > 0
    - k8s_auth_api_key | length > 0
  when: k8s_kubeconfig | string | length == 0

# Go...

- name: Deploy (without KUBECONFIG)
  block:

  - include_tasks: deploy.yaml
    when: spp_state | string == 'present'
  - include_tasks: undeploy.yaml
    when: spp_state | string == 'absent'

  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
      validate_certs: "{{ k8s_auth_verify_ssl | default('no', true) }}"

  when: k8s_kubeconfig | string | length == 0

- name: Deploy (with KUBECONFIG)
  block:

  - include_tasks: deploy.yaml
    when: spp_state | string == 'present'
  - include_tasks: undeploy.yaml
    when: spp_state | string == 'absent'

  module_defaults:
    group/k8s:
      kubeconfig: "{{ k8s_kubeconfig }}"

  when: k8s_kubeconfig | string | length > 0
