---

spp_state: present

# A namespace to deploy the Pod.
# This MUST be defined.
spp_namespace:

# Ping payload size and interval
spp_ping_size: 256
spp_ping_interval: 20s

# Prometheus scrape interval.
spp_scrape_interval: 20s

# The cluster node name,
# used as the `nodeName` as a node selector in the Deployment spec.
# Used to force the Pod onto a specific Node.
# This MUST BE defined.
spp_node_name:
# The list of peer nodes to 'ping',
# We tend to include other workers and the control nodes.
# At lest one host must be defined.
spp_hosts: []

# The Pod Security Policy (expected to exist in the cluster)
# that is used by the stack Role object.
# Where a PSP is required this must be set.
spp_sa_psp:

spp_image_registry: quay.io
spp_image_image: superq/smokeping-prober
spp_image_tag: latest
